version: '2' # specify docker-compose version

services: # Define the services/containers to be run
  database: # name of the third service
    image: mongo # specify image to build container from
    container_name: devops-database #Name of container
    ports:
      - "27017:27017" # specify port forewarding
    deploy:
      resources: #Set resource limits that will get translated to Fargate task size values
        limits:
          cpus: '0.25'
          memory: 512M
      x-aws-autoscaling: #Set a CPU percent target
        min: 2 #Min: This is the minimum number of instances that have to be there in your Autoscaling Group at all times
        max: 3 #Max: This is the maximum number of instances that your autoscaling group can have. 
        cpu: 75  #cpu or memory to define target metric, expressed as resource usage percent.
        # mem: - mutualy exlusive with cpu

  angular: # name of the first service
    build: frontend # specify the directory of the Dockerfile
    image: danoro06/devops-frontend:pdn #Name of the image created
    container_name: devops-frontend #Name of container
    ports:
      - "4200:4200" # specify port forewarding
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
      x-aws-autoscaling: #Set a CPU percent target
        min: 1 #Min: This is the minimum number of instances that have to be there in your Autoscaling Group at all times
        max: 1 #Max: This is the maximum number of instances that your autoscaling group can have. 
        cpu: 75  #cpu or memory to define target metric, expressed as resource usage percent.
        # mem: - mutualy exlusive with cpu
  
  express: #name of the second service
    build: backend # specify the directory of the Dockerfile
    image: danoro06/devops-backend:pdn #Name of the image created
    container_name: devops-backend #Name of container
    ports:
      - "3000:3000" #specify ports forewarding
    depends_on:
      - "database" #Backend needs the database is running first
    links:
      - database
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 1024M
      x-aws-autoscaling: #Set a CPU percent target
        min: 1 #Min: This is the minimum number of instances that have to be there in your Autoscaling Group at all times
        max: 1 #Max: This is the maximum number of instances that your autoscaling group can have. 
        cpu: 75  #cpu or memory to define target metric, expressed as resource usage percent.
        # mem: - mutualy exlusive with cpu