version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  database: # name of the third service
    image: mongo # specify image to build container from
    container_name: devops-database #Name of container
    ports:
      - "27017:27017" # specify port forewarding

  angular: # name of the first service
    build: frontend # specify the directory of the Dockerfile
    image: danoro06/devops-frontend #Name of the image created
    container_name: devops-frontend #Name of container
    ports:
      - "4200:4200" # specify port forewarding

  express: #name of the second service
    build: backend # specify the directory of the Dockerfile
    image: danoro06/devops-backend #Name of the image created
    container_name: devops-backend #Name of container
    ports:
      - "3000:3000" #specify ports forewarding
    depends_on:
      - "database" #Backend needs the database is running first
    links:
      - database