name: Deploy to Firebase DEV on push
"on":
  push:
    branches:
      - "feature/**"
jobs:
  docker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository files
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
