name: Pipeline CI

"on":
  push:
    branches:
      - "feature/**"

jobs:
  Node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository files
        uses: actions/checkout@v2

      # - name: Install node
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: 12.x
      
      # - name: Install dependencies on Frontend
      #   working-directory: ./frontend
      #   run: |
      #     pwd
      #     npm install

      # - name: Install dependencies on Backend
      #   working-directory: ./backend
      #   run: |
      #     pwd
      #     npm install

  # Docker:
  #   runs-on: ubuntu-latest
  #   steps:

      # Docker is preinstalled in remote server
      - name: Docker version 
        run: |
          docker version

      # Docker compose is preinstalled in remote server
      - name: Docker compose version 
        run: |
          docker compose version

      - name: Build Docker images
        run: |
          docker compose build

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker images to Docker Hub
        run: |
          docker compose push
