name: Pipeline CI

"on":
  push:
    branches:
      - "feature/**"

jobs:
  PipelineCI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository files
        uses: actions/checkout@v2

      # Docker is preinstalled in remote server
      - name: Docker version 
        run: |
          docker version

      # Docker compose is preinstalled in remote server
      - name: Docker compose version 
        run: |
          docker compose version

      - name: Build Docker images
        run: |
          docker compose build

      - name: Docker tag images
        run: |
          docker tag danoro06/devops-frontend danoro06/devops-frontend:dev
          docker tag danoro06/devops-backend danoro06/devops-backend:dev

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker images to Docker Hub
        run: |
          docker compose push
